### ISSUE TITLE
No need to keep track of Injected Tabs

### ISSUE THREAD

**Issue by mubaidr** [joelspadin/SitePreferences#6]
`setTabInjected` can be called at the end of `onSaveMessage`, this way you don't have to listen to following events:

```
chrome.tabs.onRemoved.addListener(onTabRemoved);
chrome.tabs.onUpdated.addListener(onTabUpdated);
```

plus you can simplify code by getting rid of:

```
getTabInjected()
setTabInjected()
clearInjectedTabs()
```

In-short you don't have to keep track of injected tabs.

<b>Insert content when context menu activated and remove content when options saved.</b> :+1:

**Comment by joelspadin** [comment]
So, you're suggesting I un-inject the script when the popup closes? I never found a nice way to do that.

The existing code is designed so that I don't keep re-injecting the code and adding more message listeners to the page. I suppose I could just have the script try to remove all the listeners it adds and hope I don't leave any references around that prevent it from getting garbage collected.

**Comment by joelspadin** [comment]
That still leaves the question of what happens if you open the popup, then open it again before it closes. I could disable the context menu item, but then you can't open it in two tabs simultaneously. I could disable it on a per-tab basis, but then the background page has to keep track of which tabs have the popup open instead of which tabs have the script already.

**Comment by mubaidr** [comment]
This is possible to remove specific resource from document. see this for details:
https://gist.github.com/mubaidr/3216a03a1a1252646afe

> That still leaves the question of what happens if you open the popup, then open it again before it closes. I could disable the context menu item, but then you can't open it in two tabs simultaneously.

I don't think two pop-up scripts on one page can be opened twice.

**Comment by joelspadin** [comment]
I mean the page overlay that the injected script generates. If I inject the
script each time you click the context menu, you'd get a new pop-up each
time, even if one is already open. I could have the injected script check
for the presence of the pop-up and immediately unload itself though. That
would prevent it from being injected multiple times.

**Comment by mubaidr** [comment]
> I mean the page overlay that the injected script generates. If I inject the
> script each time you click the context menu, you'd get a new pop-up each
> time, even if one is already open. I could have the injected script check
> for the presence of the pop-up and immediately unload itself though. That
> would prevent it from being injected multiple times.

Yes, this is a problem, but you can check if pop-up container with id (`__ext_site_preferences_overlay__`) is visible or present?

(I would like to contribute myself to this code but i only work in JS, but i will try)

**Comment by joelspadin** [comment]
Yeah. That's what I meant by checking for the presence of the pop-up.

**Comment by mubaidr** [comment]
Any update?

**Comment by joelspadin** [comment]
I haven't looked into this yet. The issue where things don't work after you've disabled JavaScript on a site is higher priority, since that actually breaks things. (I also did nothing this weekend but watch the entirety of Eureka Seven, so I haven't made any progress towards that either, but the hardest part of fixing that should be finding/making an icon that looks nice.)
